experiments:
    -   model: "uda-rppg"
        repetition: 1
        params:
            epoch: 100
            size: 128
            length: 600
            num_workers: 4

        stages:
            #train, inference, [FUTURE: tsne, saliency]
            # -   stage: "train"
            #     train: ["tokyo_all", "car_all"]
            #     preload: true
            #     shuffle: true
            #     fixed_sample: false
            #     sample: 2
            #     batch_size: 2
                
            -   stage: "inference"
                train: ["tokyo_all", "car_all"]
                eval: ["indoor_all"] 
                preload: false
                shuffle: false
                fixed_sample: true
                sample: null
                batch_size: 2
  
            # -   stage: "train"
            #     train: ["car_all", "indoor_all"]
            #     preload: true
            #     shuffle: true
            #     fixed_sample: false
            #     sample: 2
            #     batch_size: 2
            # -   stage: "inference"
            #     train: ["car_all", "indoor_all"]
            #     eval: ["tokyo_all"] 
            #     preload: true
            #     shuffle: false
            #     fixed_sample: true
            #     sample: null
            #     batch_size: 2

            # -   stage: "train"
            #     train: ["tokyo_all", "indoor_all"]
            #     preload: true
            #     shuffle: true
            #     fixed_sample: false
            #     sample: 2
            #     batch_size: 2

            # -   stage: "inference"
            #     train: ["tokyo_all", "indoor_all"]
            #     eval: ["car_all"] 
            #     preload: true
            #     shuffle: false
            #     fixed_sample: true
            #     sample: null
            #     batch_size: 2